### ISSUE TITLE
Can get the  train data?

### ISSUE THREAD

**Issue by YangZhou118411** [Saumil-Agarwal/LogFacies-Competition-CrowdAnalytix#1]

**Comment by Saumil-Agarwal** [comment]
https://www.crowdanalytix.com/contests/gamma-log-facies-type-prediction - Data was used from the competition provided at this website. Please not that the participants of the competition complained that the dataset had a leak in it.

**Comment by YangZhou118411** [comment]
Thanks i have got it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Saumil Agarwal"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 晚上9:48
收件人: "Saumil-Agarwal/LogFacies-Competition-CrowdAnalytix"<LogFacies-Competition-CrowdAnalytix@noreply.github.com&gt;; 
抄送: "周洋"<1925451853@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Saumil-Agarwal/LogFacies-Competition-CrowdAnalytix] Can get the  train data? (#1)





 
https://www.crowdanalytix.com/contests/gamma-log-facies-type-prediction - Data was used from the competition provided at this website. Please not that the participants of the competition complained that the dataset had a leak in it.
